l_english: 
 DIVISION_QUEUED:0 "$N$ Sư đoàn"
 DIVISIONS_QUEUED:0 "$N$ Sư đoàn"
 CONVEYOR_EQUIPMENT_NEED:0 "Trang bị cần thiết:"
 CONVEYOR_MANPOWER_NEED:0 "Nhân lực cần thiết: $AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL:0 "Sư đoàn"
 DEPLOYMENT_PROGRESS_LABEL:0 "Tiến độ"
 DEPLOYMENT_PRIORITY_LABEL:0 "Ưu tiên"
 DEPLOYMENT_DEPLOY_LABEL:0 "Triển khai"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§GClick để thêm vào hàng đợi Triển khai§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§GClick để sao chép sang các mẫu có thể triển khai của chúng ta§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§GClick để chỉnh sửa mẫu sư đoàn§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§GClick để xem mẫu phân sư đoàn§!"
 DEPLOYMENT_TRAINING:0 "Huấn luyện: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ ( Kinh nghiệm tối đa khi triển khai phụ thuộc vào số lượng trang bị )"
 DEPLOYMENT_CURRENT_LEVEL:0 "Mức độ triển khai hiện tại là $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_MANPOWER_DESC:0 "Nhân lực: $VALUE|Y0$ ( Tối đa $MAX|Y0$ )"
 DEPLOYMENT_EXPERIENCE_DESC:0 "\nNếu quá trình huấn luyện hoàn thành, đơn vị này sẽ có đủ kinh nghiệm để triển khai ở cấp độ $NUMBER$ ( $MAXLEVEL|%Y0$ ) với sửa đổi chiến đấu là $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\n Nếu đơn vị này được trang bị đầy đủ, khóa huấn luyện sẽ kết thúc vào ngày §Y$DATE$§!"
 DEPLOYMENT_EQUIPMENT:0 "Trang bị: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER:0 "Thiết kế Sư đoàn"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_ADD_TEMPLATE:0 "Huấn luyện"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "Chúng ta có thể huấn luyện tối đa $CAP|*H$ lính.\nĐược giới hạn bởi nhân lực tối đa trong lĩnh vực này ( $RATIO|H0%$ của $INFIELD|*H$. Tối thiểu: $MINPOSSIBLE|*H$ lính)"
 REGIMENTS_SELECTION_CANCEL:0 "Quay lại"
 ONLY_ONE_TEMPLATE_LEFT:0 "Bạn không thể xóa mẫu cuối cùng của mình."
 DELETE_TEMPLATE:0 "§RXóa§! mẫu khỏi danh sách."
 DELETE_TEMPLATE_TITLE:0 "Xóa Mẫu"
 DELETE_TEMPLATE_DESC:0 "Bạn có chắc chắn xóa mẫu này không?"
 DEPLOYMENT_REMOVE_DIVISION:0 "Hủy bỏ sư đoàn"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "Tuyển dụng & Triển khai"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "Không thể §RTriển khai§! một đơn vị không có bất kỳ trang bị nào.\nVui lòng đợi cho đến khi triển khai này nhận được một số trang bị."
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "Không thể §RTriển khai§! một đơn vị không có bất kỳ lính nào."
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "Không thể §RTriển khai§! một đơn vị mà không có ít nhất $VALUE|1H%$ đã huấn luyện (Hiện tại $CURRENT|1R%$)"
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "Không thể §RTriển khai§! một đơn vị mà có thể đưa chúng ta vượt quá giới hạn của lực lượng đặc biệt"
 DEPLOYMENT_HOW_TO_DESC:0 "Chọn các triển khai từ danh sách, sau đó §Gclick§! vào các tỉnh được đánh dấu trên bản đồ để triển khai.\n§gCác đơn vị được triển khai với trang bị chưa hoàn thiện sẽ tìm cách bổ sung chúng thông qua các yêu cầu tăng viện.\nHãy xem xét rằng các đơn vị triển khai quá sớm sẽ không được đào tạo thích hợp.§!"
 OPERATIONS_DESC:1 "§YHoạt động§!\n§TĐặt mức độ ưu tiên cho trang thiết bị chuẩn bị và thực hiện các hoạt động§!"
 OPERATIONS_EMPTY:0 "§GKhông có yêu cầu hiện tại cho hoạt động.§!"
 REINFORCEMENT:0 "Tăng viện"
 REINFORCEMENT_DESC:1 "§YTăng viện§!\n§TĐặt mức độ ưu tiên cho các trang thiết bị sẽ tăng viện binh lính đang hoạt động so với hàng đợi triển khai và nâng cấp§!"
 REINFORCEMENT_EMPTY:0 "§GKhông có yêu cầu hiện tại cho trang bị.§!"
 UPGRADES:0 "Nâng cấp"
 UPGRADES_DESC:1 "§YNâng cấp§!\n§TĐặt mức độ ưu tiên cho trang thiết bị sẽ nâng cấp binh lính đang hoạt động so với hàng đợi triển khai và quân tiếp viện§!"
 UPGRADES_EMPTY:0 "§GKhông có yêu cầu hiện tại cho nâng cấp.§!"
 group_infantry_title:0 "Tiểu đoàn Bộ binh"
 group_mobile_title:0 "Tiểu đoàn Cơ động"
 group_armor_title:0 "Tiểu đoàn Thiết giáp"
 group_support_title:1 "Đại đội tiếp vận"
 NEW_GROUP_ADDITIONAL_COST:0 "Nhóm mới $VALUE|H0$£army_experience£"
 GARRISONS:0 "Lực lượng Đồn trú"
 GARRISONS_DESC:1 "§YLực lượng Đồn trú§!\n§TĐặt mức độ ưu tiên cho trang bị sẽ đến lực lượng đồn trú§!"
 GARRISONS_EMPTY:0 "§GKhông có yêu cầu hiện tại cho lực lượng đồn trú.§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$ chống lại $COUNTRY$"
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ chống lại $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§TĐặt mức độ ưu tiên cho các trang bị sẽ hỗ trợ hoạt động ngoại giao này.§!"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§GTối đa trang bị đã được thu thập.§!"
 LAND_DEPLOYMENT:0 "§TTriển khai Lục quân§!"
 AIR_DEPLOYMENT:0 "§TTriển khai Hải quân§!"
 NAVAL_DEPLOYMENT:0 "§TTriển khai Không quân§!"
 DIVISION_DESIGNER_RENAME:0 "Đổi tên"
 DIVISION_DESIGNER_UPDATE:0 "Cập nhật"
 DEPLOY:0 "Triển khai"
 EDIT:0 "Chỉnh sửa"
 VIEW:0 "Xem"
 COPY:0 "Sao chép"
 DIVISION_EQUIPMENT:1 "Trang bị"
 NEW_EQUIPMENT_ALLOWED:0 "Sử dụng trang bị mới"
 DO_NOT_CONTAINS_TEMPLATE:0 "§RKhông thể xóa Mẫu này. Quốc gia không chứa Mẫu này.§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§RKhông thể xóa Mẫu này vì $AMOUNT|H$ Sư đoàn đang sử dụng nó.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§RKhông thể xóa Mẫu này vì $AMOUNT|H$ Sư đoàn đang chuyển đổi từ mẫu này sang mẫu mới (Đang chờ nhận trang bị phù hợp với mẫu mới).§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "Không thể §RXóa§! mẫu này khỏi quốc gia. Quốc gia có $AMOUNT|H$ triển khai bằng cách sử dụng mẫu này."
 HAS_GARRISON_WITH_TEMPLATE:0 "§RKhông thể xóa Mẫu này vì nó đang được sử dụng làm Mẫu Lực lượng Đồn trú cho một số vùng lãnh thổ bị chiếm đóng.§!"
 DEPLOYMENT_TEMPLATE_LABEL:0 "Mẫu"
 TEMPLATE_PRIO_0:0 "Dự trữ"
 TEMPLATE_PRIO_0_DESC:0 "Các đơn vị có mẫu này sẽ nhận được trang bị cuối cùng và ở mức ưu tiên thấp nhất sau khi được triển khai. Hoàn hảo cho các đơn vị được thiết lập để bảo vệ căn cứ và những thứ như vậy."
 TEMPLATE_PRIO_1:0 "Mặc định"
 TEMPLATE_PRIO_1_DESC:0 "Các đơn vị có mẫu này được ưu tiên trung bình cho trang bị và cường hóa sau khi được triển khai."
 TEMPLATE_PRIO_2:0 "Ưu tú"
 TEMPLATE_PRIO_2_DESC:0 "Các đơn vị có mẫu này sẽ nhận được trang bị trước bất kỳ ai khác một khi được triển khai và ở mức ưu tiên cao nhất. Sử dụng cho những người giỏi nhất của bạn và nơi họ có thể làm tốt nhất."
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "Cho vay-Cho thuê: $COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "Thêm Đơn vị"
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "Thêm đơn vị khác của $CONVEYOR|H$ sẽ được sản xuất song song.\n\n§GShift+Click§! để thêm 5 hàng"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "Nhập vào đây để thay đổi tên chung triển khai."
 CONVEYOR_TEMPLATE_ICON_DESC:0 "Việc triển khai này tạo ra các sư đoàn bằng cách sử dụng mẫu $TEMPLATE|H$."
 CANCEL_CONVEYOR_TOOLTIP:0 "§RHủy bỏ§! sản xuất tất cả các dây chuyền triển khai."
 DEPLOY_CONVEYOR_TOOLTIP:0 "§GClick§! để triển khai tất cả các hàng ngay lập tức."
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "Không có bất kỳ triển khai nào sẵn sàng cho §RTriển khai§!."
 CONVEYOR_CANCEL_TITLE:0 "§RHủy bỏ§! Sản xuất"
 CONVEYOR_CANCEL_DESC:0 "Bạn có chắc chắn muốn §RHủy bỏ§! sản xuất tất cả các dây chuyền triển khai?"
 CONVEYOR_LINE_CANCEL_DESC:0 "§RHủy bỏ§! sản xuất dây chuyền này."
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "§RHủy bỏ§! dây chuyền triển khai."
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "Bạn có chắc chắn muốn §RHủy bỏ§! sản xuất dây chuyền triển khai này không?\n(Quá trình triển khai cũng sẽ §RXóa bỏ§!)"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "Bạn có chắc chắn muốn §RHủy bỏ§! sản xuất dây chuyền triển khai này không?"
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§GClick§! để chỉ định việc triển khai theo thứ tự.\n§GClick Chuột phải§! để đặt lại mệnh lệnh chỉ định."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "Việc triển khai phải có ít nhất một thứ tự kịch bản để được chỉ định cho bất kỳ nhóm nào."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "Việc triển khai phải có vị trí mục tiêu để được chỉ định cho bất kỳ nhóm nào."
 CONVEYOR_SET_LOCATION_DESC:0 "§GClick§! để đặt vị trí triển khai cho việc triển khai này.\n§GClick Chuột phải§! để đặt lại vị trí."
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§GClick§! để đặt vị trí triển khai cho việc triển khai này.\n§GClick Chuột phải§! để đặt lại vị trí.\n§YĐây là mẫu thuộc địa và chỉ có thể được triển khai ở nước xuất xứ!§!"
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§RKhông có vị trí thiết đặt§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "Nhập vào đây để thay đổi tiền tố hàng hiện tại."
 CONVEYOR_LINE_DEPLOY_DESC:0 "§GClick§! để triển khai hàng này ngay lập tức."
 CONVEYOR_SERIES_INCREASE_DESC:0 "Tăng số lượng huấn luyện nối tiếp của các sư đoàn mà mỗi hàng sẽ hoàn thành.\n\nĐặt thành vô hạn có nghĩa là mỗi hàng sẽ đào tạo một sư đoàn mới khi một sư đoàn trước đó được triển khai."
 CONVEYOR_SERIES_AMOUNT_DESC:0 "Đây là số lượng sư đoàn mà mỗi hàng sẽ đào tạo trước khi bị xóa.\n\nĐặt thành vô hạn có nghĩa là mỗi hàng sẽ đào tạo một sư đoàn mới khi một sư đoàn trước đó được triển khai."
 CONVEYOR_SERIES_DECREASE_DESC:0 "Giảm số lượng huấn luyện nối tiếp của các sư đoàn mà mỗi hàng sẽ hoàn thành.\n\nĐặt thành vô hạn có nghĩa là mỗi hàng sẽ đào tạo một sư đoàn mới khi một sư đoàn trước đó được triển khai."
 CONVEYOR_LOW_PRIORITY_DESC:0 "Ưu tiên tăng viện thấp"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "Ưu tiên tăng viện trung bình"
 CONVEYOR_HIGH_PRIORITY_DESC:0 "Ưu tiên tăng viện cao"
 CONVEYOR_CAN_NOT_TRAIN:0 "§RKhông đủ trang bị để huấn luyện§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§RKhông đủ nhân lực để huấn luyện§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§RNot enough manpower or equipment to train $DIVS|H$ of the divisions§!"
 CONVEYOR_COLLAPSE_DESC:0 "§GClick§! để thu gọn"
 CONVEYOR_EXPAND_DESC:0 "§GClick§! để mở rộng"
 CONVEYOR_MOVE_UP:0 "§GClick§! để di chuyển xuống\n§GShift+Click§! để di chuyển lên trên đầu"
 CONVEYOR_MOVE_DOWN:0 "§GClick§! để di chuyển xuống\n§GShift+Click§! để di chuyển xuống dưới cùng"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "Ưu tiên trang bị thấp"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "Ưu tiên trang bị trung bình"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "Ưu tiên trang bị cao"
 CONVEYOR_HAS_BAD_LOCATION:0 "Vị trí mục tiêu là §RKhông hợp lệ§! để triển khai ngay bây giờ."
 CONVEYOR_TRAINING_NOT_FINISHED:0 "Huấn luyện của hàng này vẫn chưa kết thúc."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "Số loạt triển khai hiện tại trong hàng."
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§HXóa tên tùy chỉnh.§!\nSẽ cố gắng khôi phục tên được chỉ định ban đầu, trừ khi nó đã được sử dụng."
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§HChọn một tên lịch sử khác.§!\n§GClick§! để mở danh sách tất cả các tên lịch sử vẫn có sẵn. Có thể thay đổi nhóm tên bằng cách chỉnh sửa mẫu."
 DEPLOYMENT_LINE_EDIT_NAME:0 "§GClick§! và nhập, để sử dụng tên tùy chỉnh."
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§gNgoài những cái tên lịch sử.§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§RKhông đủ giới hạn lực lượng đặc biệt§!"
 TRAINING_HALTED:0 "Huấn luyện đã bị tạm dừng\n"
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "Không thể xóa các mẫu đặc biệt."
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "Không thể huấn luyện mẫu sư đoàn đặc biệt mới."
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "Với tư cách là §HChính phủ Lưu vong§! chúng ta phải kiểm soát một §HThủ đô§! để huấn luyện sư đoàn mới."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "Không thể thay đổi thành mẫu này vì điều đó sẽ khiến chúng ta vượt quá giới hạn lực lượng đặc biệt của mình"
 NO_SPECIAL_FORCES:0 "Mẫu này không chứa bất kỳ lực lượng đặc biệt nào"
 SPECIAL_FORCES_IN_TEMPLATE:0 "Mẫu này chứa $NUM|Y$ tiểu đoàn đặc biệt"
 SPECIAL_FORCES_CAP_DESC:0 "Bạn hiện đang trang bị $USED|Y$ và huấn luyện $IN_TRAINING|Y$ trong tổng số $CAP|Y$ tiểu đoàn đặc biệt được phép của chúng ta"
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "Điều này để lại chỗ cho $TRAINABLE|Y$ sư đoàn bằng cách sử dụng mẫu này."
 SHOW_DECOMMISSIONED_TEMPLATES:0 "Show §Hdecommissioned templates§!"
 DECOMMISSION_TEMPLATE_TOGGLE_ON:0 "Decommission"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC:0 "§GClick§! to decommission this template, marking it as retired."
 DECOMMISSION_TEMPLATE_TOGGLE_OFF:0 "Recommission"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC:0 "§GClick§! to recommission this template, marking it as in service."
